// Generated by CoffeeScript 1.9.1
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

module.exports = function(env) {
  var ConnectionProvider, EventEmitter, KodiApi, KodiExecuteOpenActionHandler, KodiExecuteOpenActionProvider, KodiNextActionHandler, KodiNextActionProvider, KodiPauseActionHandler, KodiPauseActionProvider, KodiPlayActionHandler, KodiPlayActionProvider, KodiPlayer, KodiPlugin, KodiPrevActionHandler, KodiPrevActionProvider, M, PlayingPredicateHandler, PlayingPredicateProvider, Promise, VERBOSE, _, assert, kodiPlugin;
  Promise = env.require('bluebird');
  assert = env.require('cassert');
  EventEmitter = require('events').EventEmitter;
  KodiApi = require('xbmc-ws');
  VERBOSE = false;
  M = env.matcher;
  _ = env.require('lodash');
  KodiPlugin = (function(superClass) {
    extend(KodiPlugin, superClass);

    function KodiPlugin() {
      this.init = bind(this.init, this);
      return KodiPlugin.__super__.constructor.apply(this, arguments);
    }

    KodiPlugin.prototype.init = function(app, framework, config1) {
      var deviceConfigDef;
      this.framework = framework;
      this.config = config1;
      env.logger.info("Kodi plugin started");
      deviceConfigDef = require("./device-config-schema");
      this.framework.deviceManager.registerDeviceClass("KodiPlayer", {
        configDef: deviceConfigDef.KodiPlayer,
        createCallback: (function(_this) {
          return function(config) {
            return new KodiPlayer(config);
          };
        })(this)
      });
      this.framework.ruleManager.addActionProvider(new KodiPauseActionProvider(this.framework));
      this.framework.ruleManager.addActionProvider(new KodiPlayActionProvider(this.framework));
      this.framework.ruleManager.addActionProvider(new KodiPrevActionProvider(this.framework));
      this.framework.ruleManager.addActionProvider(new KodiNextActionProvider(this.framework));
      this.framework.ruleManager.addActionProvider(new KodiExecuteOpenActionProvider(this.framework, this.config));
      return this.framework.ruleManager.addPredicateProvider(new PlayingPredicateProvider(this.framework));
    };

    return KodiPlugin;

  })(env.plugins.Plugin);
  ConnectionProvider = (function(superClass) {
    extend(ConnectionProvider, superClass);

    ConnectionProvider.prototype.connection = null;

    ConnectionProvider.prototype.connected = false;

    ConnectionProvider.prototype._host = "";

    ConnectionProvider.prototype._port = 0;

    ConnectionProvider.prototype._emitter = null;

    function ConnectionProvider(host, port) {
      this.getConnection = bind(this.getConnection, this);
      this._host = host;
      this._port = port;
    }

    ConnectionProvider.prototype.getConnection = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          if (_this.connected) {
            return resolve(_this.connection);
          } else {
            return KodiApi(_this._host, _this._port).then(function(newConnection) {
              _this.connected = true;
              _this.connection = newConnection;
              _this.emit('newConnection');
              _this.connection.on("error", (function() {
                _this.connected = false;
                return _this.connection = null;
              }));
              _this.connection.on("close", (function() {
                _this.connected = false;
                return _this.connection = null;
              }));
              return resolve(_this.connection);
            })["catch"](function(error) {
              env.logger.debug('connection rejected');
              return env.logger.debug(error);
            });
          }
        };
      })(this));
    };

    return ConnectionProvider;

  })(EventEmitter);
  KodiPlayer = (function(superClass) {
    extend(KodiPlayer, superClass);

    KodiPlayer.prototype._state = "stopped";

    KodiPlayer.prototype._type = "";

    KodiPlayer.prototype._currentTitle = null;

    KodiPlayer.prototype._currentArtist = null;

    KodiPlayer.prototype._volume = null;

    KodiPlayer.prototype._host = "";

    KodiPlayer.prototype._port = 0;

    KodiPlayer.prototype._connectionProvider = null;

    KodiPlayer.prototype.kodi = null;

    KodiPlayer.prototype.actions = {
      play: {
        description: "starts playing"
      },
      pause: {
        description: "pauses playing"
      },
      stop: {
        description: "stops playing"
      },
      next: {
        description: "play next song"
      },
      previous: {
        description: "play previous song"
      },
      volume: {
        description: "Change volume of player"
      },
      executeOpenCommand: {
        description: "Execute custom Player.Open command"
      }
    };

    KodiPlayer.prototype.attributes = {
      currentArtist: {
        description: "the current playing track artist",
        type: "string"
      },
      currentTitle: {
        description: "the current playing track title",
        type: "string"
      },
      state: {
        description: "the current state of the player",
        type: "string"
      },
      type: {
        description: "The current type of the player",
        type: "string"
      },
      volume: {
        description: "the volume of the player",
        type: "string"
      }
    };

    KodiPlayer.prototype.template = "musicplayer";

    function KodiPlayer(config1) {
      var _host, _port, _state;
      this.config = config1;
      this.executeOpenCommand = bind(this.executeOpenCommand, this);
      this.name = this.config.name;
      this.id = this.config.id;
      _host = this.config.host;
      _port = this.config.port;
      _state = 'stopped';
      this._connectionProvider = new ConnectionProvider(this.config.host, this.config.port);
      this._connectionProvider.on('newConnection', (function(_this) {
        return function() {
          return _this._connectionProvider.getConnection().then(function(connection) {
            connection.Player.OnPause(function(data) {
              env.logger.debug('Kodi Paused');
              _this._setState('paused');
            });
            connection.Player.OnStop(function() {
              env.logger.debug('Kodi Paused');
              _this._setState('stopped');
              _this._setCurrentTitle('');
              _this._setCurrentArtist('');
            });
            return connection.Player.OnPlay(function(data) {
              var ref;
              if ((data != null ? (ref = data.data) != null ? ref.item : void 0 : void 0) != null) {
                _this._parseItem(data.data.item);
              }
              env.logger.debug('Kodi Playing');
              _this._setState('playing');
            });
          });
        };
      })(this));
      this._updateInfo();
      setInterval((function(_this) {
        return function() {
          return _this._updateInfo();
        };
      })(this), 60000);
      KodiPlayer.__super__.constructor.call(this);
    }

    KodiPlayer.prototype.getState = function() {
      return Promise.resolve(this._state);
    };

    KodiPlayer.prototype.getCurrentTitle = function() {
      return Promise.resolve(this._currentTitle);
    };

    KodiPlayer.prototype.getCurrentArtist = function() {
      return Promise.resolve(this._currentTitle);
    };

    KodiPlayer.prototype.getVolume = function() {
      return Promise.resolve(this._volume);
    };

    KodiPlayer.prototype.getType = function() {
      return Promise.resolve(this._type);
    };

    KodiPlayer.prototype.play = function() {
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.GetActivePlayers().then(function(players) {
            if (players.length > 0) {
              return connection.Player.PlayPause({
                "playerid": players[0].playerid
              });
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype.pause = function() {
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.GetActivePlayers().then(function(players) {
            if (players.length > 0) {
              return connection.Player.PlayPause({
                "playerid": players[0].playerid
              });
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype.stop = function() {
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.GetActivePlayers().then(function(players) {
            if (players.length > 0) {
              return connection.Player.Stop({
                "playerid": players[0].playerid
              });
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype.previous = function() {
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.GetActivePlayers().then(function(players) {
            if (players.length > 0) {
              return connection.Player.GoTo({
                "playerid": players[0].playerid,
                "to": "previous"
              });
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype.next = function() {
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.GetActivePlayers().then(function(players) {
            if (players.length > 0) {
              return connection.Player.GoTo({
                "playerid": players[0].playerid,
                "to": "next"
              });
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype.setVolume = function(volume) {
      return env.logger.debug('setVolume not implemented');
    };

    KodiPlayer.prototype.executeOpenCommand = function(command) {
      env.logger.debug(command);
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.Open({
            item: {
              file: command
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype._updateInfo = function() {
      return Promise.all([this._updatePlayer()]);
    };

    KodiPlayer.prototype._setState = function(state) {
      if (this._state !== state) {
        this._state = state;
        return this.emit('state', state);
      }
    };

    KodiPlayer.prototype._setType = function(type) {
      if (this._type !== type) {
        this._type = type;
        return this.emit('type', type);
      }
    };

    KodiPlayer.prototype._setCurrentTitle = function(title) {
      if (this._currentTitle !== title) {
        this._currentTitle = title;
        return this.emit('currentTitle', title);
      }
    };

    KodiPlayer.prototype._setCurrentArtist = function(artist) {
      if (this._currentArtist !== artist) {
        this._currentArtist = artist;
        return this.emit('currentArtist', artist);
      }
    };

    KodiPlayer.prototype._setVolume = function(volume) {
      if (this._volume !== volume) {
        this._volume = volume;
        return this.emit('volume', volume);
      }
    };

    KodiPlayer.prototype._updatePlayer = function() {
      env.logger.debug('_updatePlayer');
      return this._connectionProvider.getConnection().then((function(_this) {
        return function(connection) {
          return connection.Player.GetActivePlayers().then(function(players) {
            if (players.length > 0) {
              return connection.Player.GetItem({
                "playerid": players[0].playerid,
                "properties": ["title", "artist"]
              }).then(function(data) {
                var info;
                env.logger.debug(data);
                info = data.item;
                _this._setCurrentTitle(info.title != null ? info.title : info.label != null ? info.label : "");
                _this._setCurrentArtist(info.artist != null ? info.artist : "");
                return _this._setType(info.type);
              });
            } else {
              _this._setCurrentArtist('');
              return _this._setCurrentTitle('');
            }
          });
        };
      })(this));
    };

    KodiPlayer.prototype._sendCommandAction = function(action) {
      return this.kodi.input.ExecuteAction(action);
    };

    KodiPlayer.prototype._parseItem = function(itm) {
      var artist, ref, ref1, ref2, title, type;
      if (itm != null) {
        artist = (ref = (ref1 = itm.artist) != null ? ref1[0] : void 0) != null ? ref : itm.artist;
        title = itm.title;
        type = (ref2 = itm.type) != null ? ref2 : '';
        this._setType(type);
        env.logger.debug(title);
        if (type === 'song' || ((title != null) && (artist != null))) {
          this._setCurrentTitle(title != null ? title : "");
          this._setCurrentArtist(artist != null ? artist : "");
        }
        return this._updateInfo();
      }
    };

    return KodiPlayer;

  })(env.devices.Device);
  KodiExecuteOpenActionProvider = (function(superClass) {
    extend(KodiExecuteOpenActionProvider, superClass);

    function KodiExecuteOpenActionProvider(framework, config1) {
      this.framework = framework;
      this.config = config1;
      this.parseAction = bind(this.parseAction, this);
    }


    /*
    This function handles action in the form of `execute "some string"`
     */

    KodiExecuteOpenActionProvider.prototype.parseAction = function(input, context) {
      var command, commandNames, device, i, kodiPlayers, len, m, match, onDeviceMatch, ref, ref1, retVar, state;
      retVar = null;
      kodiPlayers = _(this.framework.deviceManager.devices).values().filter((function(_this) {
        return function(device) {
          return device.hasAction("executeOpenCommand");
        };
      })(this)).value();
      if (kodiPlayers.length === 0) {
        return;
      }
      device = null;
      match = null;
      state = null;
      commandNames = [];
      ref = this.config.customOpenCommands;
      for (i = 0, len = ref.length; i < len; i++) {
        command = ref[i];
        commandNames.push(command.name);
      }
      onDeviceMatch = (function(m, d) {
        device = d;
        return match = m.getFullMatch();
      });
      m = M(input, context).match('execute Open Command ').match(commandNames, function(m, s) {
        return state = s.trim();
      }).match(' on ').matchDevice(kodiPlayers, onDeviceMatch);
      if (match != null) {
        assert(device != null);
        assert((ref1 = state, indexOf.call(commandNames, ref1) >= 0));
        assert(typeof match === "string");
        return {
          token: match,
          nextInput: input.substring(match.length),
          actionHandler: new KodiExecuteOpenActionHandler(device, this.config, state)
        };
      } else {
        return null;
      }
    };

    return KodiExecuteOpenActionProvider;

  })(env.actions.ActionProvider);
  KodiExecuteOpenActionHandler = (function(superClass) {
    extend(KodiExecuteOpenActionHandler, superClass);

    function KodiExecuteOpenActionHandler(device1, config1, name) {
      this.device = device1;
      this.config = config1;
      this.name = name;
      this.executeAction = bind(this.executeAction, this);
    }

    KodiExecuteOpenActionHandler.prototype.executeAction = function(simulate) {
      var command, i, j, len, len1, ref, ref1;
      if (simulate) {
        ref = this.config.customOpenCommands;
        for (i = 0, len = ref.length; i < len; i++) {
          command = ref[i];
          if (command.name === this.name) {
            return Promise.resolve(__("would execute %s", command.command));
            console.log('resolved');
          }
        }
      } else {
        ref1 = this.config.customOpenCommands;
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          command = ref1[j];
          env.logger.debug("checking for: " + command.name + " == " + this.name);
          if (command.name === this.name) {
            return this.device.executeOpenCommand(command.command).then((function(_this) {
              return function() {
                return __("executed %s", _this.device.name);
              };
            })(this));
            console.log('executed');
          }
        }
      }
    };

    return KodiExecuteOpenActionHandler;

  })(env.actions.ActionHandler);
  KodiPauseActionProvider = (function(superClass) {
    extend(KodiPauseActionProvider, superClass);

    function KodiPauseActionProvider(framework) {
      this.framework = framework;
      this.parseAction = bind(this.parseAction, this);
    }


    /*
    This function handles action in the form of `execute "some string"`
     */

    KodiPauseActionProvider.prototype.parseAction = function(input, context) {
      var device, kodiPlayers, m, match, onDeviceMatch, retVar;
      retVar = null;
      kodiPlayers = _(this.framework.deviceManager.devices).values().filter((function(_this) {
        return function(device) {
          return device.hasAction("play");
        };
      })(this)).value();
      if (kodiPlayers.length === 0) {
        return;
      }
      device = null;
      match = null;
      onDeviceMatch = (function(m, d) {
        device = d;
        return match = m.getFullMatch();
      });
      m = M(input, context).match('pause ').matchDevice(kodiPlayers, onDeviceMatch);
      if (match != null) {
        assert(device != null);
        assert(typeof match === "string");
        return {
          token: match,
          nextInput: input.substring(match.length),
          actionHandler: new KodiPauseActionHandler(device)
        };
      } else {
        return null;
      }
    };

    return KodiPauseActionProvider;

  })(env.actions.ActionProvider);
  KodiPauseActionHandler = (function(superClass) {
    extend(KodiPauseActionHandler, superClass);

    function KodiPauseActionHandler(device1) {
      this.device = device1;
      this.executeAction = bind(this.executeAction, this);
    }

    KodiPauseActionHandler.prototype.executeAction = function(simulate) {
      return (simulate ? Promise.resolve(__("would pause %s", this.device.name)) : this.device.pause().then((function(_this) {
        return function() {
          return __("paused %s", _this.device.name);
        };
      })(this)));
    };

    return KodiPauseActionHandler;

  })(env.actions.ActionHandler);
  KodiPlayActionProvider = (function(superClass) {
    extend(KodiPlayActionProvider, superClass);

    function KodiPlayActionProvider(framework) {
      this.framework = framework;
      this.parseAction = bind(this.parseAction, this);
    }


    /*
    This function handles action in the form of `execute "some string"`
     */

    KodiPlayActionProvider.prototype.parseAction = function(input, context) {
      var device, kodiPlayers, m, match, onDeviceMatch, retVar;
      retVar = null;
      kodiPlayers = _(this.framework.deviceManager.devices).values().filter((function(_this) {
        return function(device) {
          return device.hasAction("play");
        };
      })(this)).value();
      if (kodiPlayers.length === 0) {
        return;
      }
      device = null;
      match = null;
      onDeviceMatch = (function(m, d) {
        device = d;
        return match = m.getFullMatch();
      });
      m = M(input, context).match('play ').matchDevice(kodiPlayers, onDeviceMatch);
      if (match != null) {
        assert(device != null);
        assert(typeof match === "string");
        return {
          token: match,
          nextInput: input.substring(match.length),
          actionHandler: new KodiPlayActionHandler(device)
        };
      } else {
        return null;
      }
    };

    return KodiPlayActionProvider;

  })(env.actions.ActionProvider);
  KodiPlayActionHandler = (function(superClass) {
    extend(KodiPlayActionHandler, superClass);

    function KodiPlayActionHandler(device1) {
      this.device = device1;
      this.executeAction = bind(this.executeAction, this);
    }

    KodiPlayActionHandler.prototype.executeAction = function(simulate) {
      return (simulate ? Promise.resolve(__("would play %s", this.device.name)) : this.device.play().then((function(_this) {
        return function() {
          return __("playing %s", _this.device.name);
        };
      })(this)));
    };

    return KodiPlayActionHandler;

  })(env.actions.ActionHandler);
  KodiNextActionProvider = (function(superClass) {
    extend(KodiNextActionProvider, superClass);

    function KodiNextActionProvider(framework) {
      this.framework = framework;
      this.parseAction = bind(this.parseAction, this);
    }


    /*
    This function handles action in the form of `execute "some string"`
     */

    KodiNextActionProvider.prototype.parseAction = function(input, context) {
      var device, kodiPlayers, m, match, onDeviceMatch, retVar, valueTokens, volume;
      retVar = null;
      volume = null;
      kodiPlayers = _(this.framework.deviceManager.devices).values().filter((function(_this) {
        return function(device) {
          return device.hasAction("play");
        };
      })(this)).value();
      if (kodiPlayers.length === 0) {
        return;
      }
      device = null;
      valueTokens = null;
      match = null;
      onDeviceMatch = (function(m, d) {
        device = d;
        return match = m.getFullMatch();
      });
      m = M(input, context).match(['play next', 'next ']).match(" song ", {
        optional: true
      }).match("on ").matchDevice(kodiPlayers, onDeviceMatch);
      if (match != null) {
        assert(device != null);
        assert(typeof match === "string");
        return {
          token: match,
          nextInput: input.substring(match.length),
          actionHandler: new KodiNextActionHandler(device)
        };
      } else {
        return null;
      }
    };

    return KodiNextActionProvider;

  })(env.actions.ActionProvider);
  KodiNextActionHandler = (function(superClass) {
    extend(KodiNextActionHandler, superClass);

    function KodiNextActionHandler(device1) {
      this.device = device1;
      this.executeAction = bind(this.executeAction, this);
    }

    KodiNextActionHandler.prototype.executeAction = function(simulate) {
      return (simulate ? Promise.resolve(__("would play next track of %s", this.device.name)) : this.device.next().then((function(_this) {
        return function() {
          return __("play next track of %s", _this.device.name);
        };
      })(this)));
    };

    return KodiNextActionHandler;

  })(env.actions.ActionHandler);
  KodiPrevActionProvider = (function(superClass) {
    extend(KodiPrevActionProvider, superClass);

    function KodiPrevActionProvider(framework) {
      this.framework = framework;
      this.parseAction = bind(this.parseAction, this);
    }


    /*
    This function handles action in the form of `execute "some string"`
     */

    KodiPrevActionProvider.prototype.parseAction = function(input, context) {
      var device, kodiPlayers, m, match, onDeviceMatch, retVar, valueTokens, volume;
      retVar = null;
      volume = null;
      kodiPlayers = _(this.framework.deviceManager.devices).values().filter((function(_this) {
        return function(device) {
          return device.hasAction("play");
        };
      })(this)).value();
      if (kodiPlayers.length === 0) {
        return;
      }
      device = null;
      valueTokens = null;
      match = null;
      onDeviceMatch = (function(m, d) {
        device = d;
        return match = m.getFullMatch();
      });
      m = M(input, context).match(['play previous', 'previous ']).match(" song ", {
        optional: true
      }).match("on ").matchDevice(kodiPlayers, onDeviceMatch);
      if (match != null) {
        assert(device != null);
        assert(typeof match === "string");
        return {
          token: match,
          nextInput: input.substring(match.length),
          actionHandler: new KodiNextActionHandler(device)
        };
      } else {
        return null;
      }
    };

    return KodiPrevActionProvider;

  })(env.actions.ActionProvider);
  KodiPrevActionHandler = (function(superClass) {
    extend(KodiPrevActionHandler, superClass);

    function KodiPrevActionHandler(device1) {
      this.device = device1;
      this.executeAction = bind(this.executeAction, this);
    }

    KodiPrevActionHandler.prototype.executeAction = function(simulate) {
      return (simulate ? Promise.resolve(__("would play previous track of %s", this.device.name)) : this.device.previous().then((function(_this) {
        return function() {
          return __("play previous track of %s", _this.device.name);
        };
      })(this)));
    };

    return KodiPrevActionHandler;

  })(env.actions.ActionHandler);
  PlayingPredicateProvider = (function(superClass) {
    extend(PlayingPredicateProvider, superClass);

    function PlayingPredicateProvider(framework) {
      this.framework = framework;
    }

    PlayingPredicateProvider.prototype.parsePredicate = function(input, context) {
      var device, kodiDevices, match, negated, state;
      kodiDevices = _(this.framework.deviceManager.devices).values().filter((function(_this) {
        return function(device) {
          return device.hasAttribute('state');
        };
      })(this)).value();
      device = null;
      state = null;
      negated = null;
      match = null;
      M(input, context).matchDevice(kodiDevices, (function(_this) {
        return function(next, d) {
          return next.match([' is', ' reports', ' signals']).match([' playing', ' stopped', ' paused', ' not playing'], function(m, s) {
            if ((device != null) && device.id !== d.id) {
              if (context != null) {
                context.addError("\"" + (input.trim()) + "\" is ambiguous.");
              }
              return;
            }
            device = d;
            state = s.trim();
            return match = m.getFullMatch();
          });
        };
      })(this));
      if (match != null) {
        assert(device != null);
        assert(state != null);
        assert(typeof match === "string");
        return {
          token: match,
          nextInput: input.substring(match.length),
          predicateHandler: new PlayingPredicateHandler(device, state)
        };
      } else {
        return null;
      }
    };

    return PlayingPredicateProvider;

  })(env.predicates.PredicateProvider);
  PlayingPredicateHandler = (function(superClass) {
    extend(PlayingPredicateHandler, superClass);

    function PlayingPredicateHandler(device1, state1) {
      this.device = device1;
      this.state = state1;
    }

    PlayingPredicateHandler.prototype.setup = function() {
      this.playingListener = (function(_this) {
        return function(p) {
          env.logger.debug("checking for: " + _this.state + " == " + p);
          if (_this.state.trim() === p.trim()) {
            return _this.emit('change', _this.state.trim() === p.trim());
          } else if (_this.state === "not playing" && (p.trim() !== "playing")) {
            return _this.emit('change', p.trim() !== "playing");
          }
        };
      })(this);
      this.device.on('state', this.playingListener);
      return PlayingPredicateHandler.__super__.setup.call(this);
    };

    PlayingPredicateHandler.prototype.getValue = function() {
      return this.device.getUpdatedAttributeValue('state').then((function(_this) {
        return function(p) {
          if (_this.state.trim() === p.trim()) {
            return _this.state.trim() === p.trim();
          } else if (_this.state === "not playing" && (p.trim() !== "playing")) {
            return p.trim() !== "playing";
          }
        };
      })(this));
    };

    PlayingPredicateHandler.prototype.destroy = function() {
      this.device.removeListener("state", this.playingListener);
      return PlayingPredicateHandler.__super__.destroy.call(this);
    };

    PlayingPredicateHandler.prototype.getType = function() {
      return 'state';
    };

    return PlayingPredicateHandler;

  })(env.predicates.PredicateHandler);
  kodiPlugin = new KodiPlugin;
  return kodiPlugin;
};
